# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoaderCEN_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoaderCENDialogBase(object):
    def setupUi(self, LoaderCENDialogBase):
        LoaderCENDialogBase.setObjectName("LoaderCENDialogBase")
        LoaderCENDialogBase.resize(620, 394)
        self.groupBox = QtWidgets.QGroupBox(LoaderCENDialogBase)
        self.groupBox.setGeometry(QtCore.QRect(14, 20, 591, 161))
        self.groupBox.setObjectName("groupBox")
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.groupBox)
        self.commandLinkButton_2.setGeometry(QtCore.QRect(370, 40, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.commandLinkButton_2.setFont(font)
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.groupBox)
        self.commandLinkButton.setGeometry(QtCore.QRect(30, 60, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.commandLinkButton.setFont(font)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.commandLinkButton_3 = QtWidgets.QCommandLinkButton(self.groupBox)
        self.commandLinkButton_3.setGeometry(QtCore.QRect(370, 80, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.commandLinkButton_3.setFont(font)
        self.commandLinkButton_3.setObjectName("commandLinkButton_3")
        self.groupBox_2 = QtWidgets.QGroupBox(LoaderCENDialogBase)
        self.groupBox_2.setGeometry(QtCore.QRect(14, 270, 591, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(380, 50, 161, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(50, 50, 161, 23))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(LoaderCENDialogBase)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(290, 210, 31, 31))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/plugins/LoaderCEN/arrow.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(LoaderCENDialogBase)
        self.label_2.setGeometry(QtCore.QRect(450, 200, 51, 51))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/plugins/LoaderCEN/loading.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(LoaderCENDialogBase)
        self.label_3.setGeometry(QtCore.QRect(100, 200, 51, 51))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/plugins/LoaderCEN/loading.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(LoaderCENDialogBase)
        QtCore.QMetaObject.connectSlotsByName(LoaderCENDialogBase)

    def retranslateUi(self, LoaderCENDialogBase):
        _translate = QtCore.QCoreApplication.translate
        LoaderCENDialogBase.setWindowTitle(_translate("LoaderCENDialogBase", "LoaderCEN"))
        self.groupBox.setTitle(_translate("LoaderCENDialogBase", "Choix des dalles"))
        self.commandLinkButton_2.setText(_translate("LoaderCENDialogBase", " Dalles orthos 20cm"))
        self.commandLinkButton.setText(_translate("LoaderCENDialogBase", " Dalles MNT 1 m"))
        self.commandLinkButton_3.setText(_translate("LoaderCENDialogBase", " Dalles orthos 50cm"))
        self.groupBox_2.setTitle(_translate("LoaderCENDialogBase", "Chargement des couches "))
        self.pushButton_2.setText(_translate("LoaderCENDialogBase", "Chargement des orthos"))
        self.pushButton.setText(_translate("LoaderCENDialogBase", "Chargement des dalles MNT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoaderCENDialogBase = QtWidgets.QDialog()
    ui = Ui_LoaderCENDialogBase()
    ui.setupUi(LoaderCENDialogBase)
    LoaderCENDialogBase.show()
    sys.exit(app.exec_())
