github_urls:
  info_changelog: "https://raw.githubusercontent.com/CEN-Nouvelle-Aquitaine/LoaderCEN/main/html/info_changelog.html"
depot_plugins_url:
  last_version: "https://sig.dsi-cen.org/qgis/downloads/last_version_loadercen.txt"
  